annonce_categorie:
    resource: "@AnnonceBundle/Resources/config/routing/categorie.yml"
    prefix:   /categorie
annonce_detailannonce:
    resource: "@AnnonceBundle/Resources/config/routing/detailannonce.yml"
    prefix:   /



