<?php

namespace Annonce\AnnonceBundle\Repository;

/**
 * DetailAnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailAnnonceRepository extends \Doctrine\ORM\EntityRepository
{
    public function byCategorie($categorie)
    {
        $qb=$this->createQueryBuilder('d')
            ->select('d')
            ->where('d.$categorie = :$categorie')
            ->orderBy('d.id')
            ->setParameter('categorie',$categorie);
            return $qb->getQuery()->getResult();

    }
}
