<?php

namespace Annonce\AnnonceBundle\Repository;

/**
 * DetailAnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailAnnonceRepository extends \Doctrine\ORM\EntityRepository
{

}
